---
name: 'YAML Validation'

runs:
  using: "composite"
  steps:
    - name: Validate yml extension
      shell: bash
      run: |
        find . -regex ".*\.yml$" -exec echo "::error file={},line=1,col=1:: Wrong extension" \;
        if [[ `find . -regex ".*\.yml$"` ]]; then exit 1; fi
    - shell: bash
      run: |
        echo "yamllint -f github ."
